### PR TITLE
Small bugfixes

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
Bugfixes adapted from https://github.com/Capitanloco6/Divergences-HPM/pull/25

Opened by: Outta-my-way-burrocrat

### CODE REVIEW

**Comment by Capitanloco6** [comment]
Hi, appreciate your work - maybe it's better if we coordinate in the dev section of our discord? https://discord.gg/DmyDdDxH

**Comment by Capitanloco6** [comment]
> Hi, appreciate your work - maybe it's better if we coordinate in the dev section of our discord? https://discord.gg/DmyDdDxH

Ping me (MajorMajor)

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 if patch #25 is merged this should be closed.

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 I'm going to stop posting on the 28th, so I won't be able to maintain these PRs any longer. I give y'all permission to use any of my contributions from these PRs, just don't go out of your way to hide my work or credits.

**Pull request closed without merging**
