### PR TITLE
Patch

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
Started porting over some recent content from Historical Project Mod and PDM as well
 Fixed core
 localization fix
 Fuuta Jallon unciv techs
 new_patch with https://github.com/Capitanloco6/Divergences-HPM/commit/e32aacb4d756e216499dbee33b77956c93a633e7
 Another bugfix bugfix

Here's a list of the things from HPM I can remember:

    Changed the legation quarter modifier back to a country modifier. It's also used differently.
    Added a few of the newer country and province modifiers for future use.
    Changed AI ship proportion in defines.lua.
    Opium converted directly to cash.
    Simplified central bank mechanics.
    Some religion checks in pop_types.txt
	Some unemployment-related stuff in pop_types.txt
    Infrastructure attracts immigrants.
    Started adding copenhagen_convention chain to remove the currently-permanent sound dues.
    National values selection improvements.
    Adapted the encourage_the_skoda_works tech school decision.
    Some unciv events open or close the border policies.
    Most modifiers that change pop demands are made country modifiers again to stop zero demand bug caused by pop demand modifiers applying nationally.
    Removed checks for boxer_presence
	foreign_trading_post and foreign_presence modifiers apply nationally again
    Event 14620 changes.
    Various decision images
    Some navy inventions and invention tweaks
	Some naval inventions are unlocked differently
	Ship combat tweaks
    Ship speed increase.
    Luxury clothes factory unlocked by jacquard_power_loom
    Adapted Tripoli and Libya parties.
    Countries in australia_new_zealand can benefit from immigration mechanics.
	Some leader and party modifiers and flags are removed by events
    Fixed negative social_spending modifier.
    Some decisions and events remove leader modifiers or party flags.
	local_opium_habit is made temporary
	No more liferating damage from natural disasters
	Religion flags and fixes for most countries
	Event tweaks
	Many tweaks and changes

From PDM:

    Recycled the social-liberal party names.

The monitors were removed and replaced by submarines and a series of upgrades to the commerce raider. I don't remember if this implementation was from PDM, another mod or my work.

Added an unciv pop growth bonus to stop the slow death of unciv pops caused by HPM's economic system.
Kongo event changes
Uncivs will receive free research points or higher reforms if an event gives them a reform they already have.
Restorationists renamed to Autocrats
Independence for Palestine event. I might add events for religious pluralist Palestinian monarchy encouraging Jewish immigration.
Independence for Lebanon event
No Penal Reform League if penal reform at maximum
Wake island is back
Added fixes for many New Zealand provinces
Spanish treaty port in Bissau
Changed Inca westernisation and ruling parties
Potassium in Aaiun (anachronistic)
More Catholics and Spanish pops in Africa.
More Sunnis in West Africa
Updated a few European colonist pops
Removed reference to Bambara from Bissau
Fixed Hufuf exclave

Athesia fix https://www.reddit.com/r/victoria2/comments/o69opn/dod_i_played_an_entire_game_as_athesia_florida/

Many tweaks and changes

oversight
Opened by: Outta-my-way-burrocrat

### CODE REVIEW

**Comment by Capitanloco6** [comment]
Hi! I appreciate your work, particularly the bugfixing, but I would like a list of what you ported exactly from HPM and PDM in this pull request. I am not a fan of many of the post 0.4 HPM features, and I can see that some of them are here (monitors requiring fuel, etc.)

**Comment by Outta-my-way-burrocrat** [comment]
> Hi! I appreciate your work, particularly the bugfixing, but I would like a list of what you ported exactly from HPM and PDM in this pull request. I am not a fan of many of the post 0.4 HPM features, and I can see that some of them are here (monitors requiring fuel, etc.)

@Capitanloco6 @Lys0gen 

Hi, I've been out of town for a while but I'm back for a short time. I'm probably going to delete my repository but I don't want to lose this work, please answer back as soon as you can.

Here's a list of the things from HPM I can remember:

1. Changed the legation quarter modifier back to a country modifier. It's also used differently.
2. Added a few of the newer country and province modifiers for future use.
3. Ship weights in defines.lua.
4. Opium converted directly to cash.
5. Simplified central bank mechanics.
6. pop_types.txt
7. Infrastructure attracts immigrants.
8. copenhagen_convention chain to remove the currently-permanent sound dues.
9. National values selection improvements.
10. Adapted the encourage_the_skoda_works tech school decision.
11. Some unciv events open or close the border policies.
12. Most modifiers that change pop demands are made country modifiers again to stop zero demand bug.
13. Most of CivilizationAndGunBoats
14. Event 14620 changes.
15. Various decision images
16. Some navy inventions
17. Ship speed increase.
18. Luxury clothes factory unlocked by jacquard_power_loom
19. Tripoli missing parties.
20. Countries in australia_new_zealand can benefit from immigration mechanics.


From PDM:
1. Recycled the social-liberal party names.

The monitors were removed and replaced by submarines and a series of upgrades to the commerce raider. I don't remember if this implementation was from PDM, another mod or my work.

Added an unciv pop growth bonus to stop the slow death of unciv pops caused by HPM's economic system.

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 what content from HPM would be unacceptable?

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 has development of this mod stopped today?

**Comment by Outta-my-way-burrocrat** [comment]
Ok, I've finished cleaning up oversights.

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 do you know what mod the fetishist religion came from?

**Comment by Outta-my-way-burrocrat** [comment]
Some of the content in the patch (hello code archaeologists!):
reactionary_2 is renamed Autocrats
Arabian conservatives are named Pan-Islamists
Start and end date fixes for some parties
MLI has a country file
Incan reactionary party renamed and has state capitalism and limited citizenship
Libyan party tweaks
Lebanon accepts Druze
Romani are part of the indian union group
Bakongo leaders can have spanish names
Uncivs get global_population_growth = 0.001 if their admin spending is 02 or greater
Penal reform league doesn't fire if pnal reform is at maximum
Kongo gets more unciv reforms but choosing to send children away puts them in the spanish sphere. I may add more events for spanish annexation of Kongo in another PR
Kongo can accept Ovimbundu
Kongo hates Scandinavia after they conquered Kongolese land and Spanish colonies in Angola
Lunda accepts Chokwe
More Spanish presence in Africa
Spanish Bissau
Catholic Spanish pops in Benguela
Rwanda and Burundi start with conservative parties and culture_voting_only
Scandinavian pops in Sekondi
More Sunni pops in Mali
Ancap Radical Arbeiterpartei renamed to Freiheitspartei
Tukulor renamed to Haalpulaar State

**Comment by Capitanloco6** [comment]
Hi! Apologies for the long silence, I only really check this page shortly before release. I have incorporated some of your proposed fixes and cleanup, and I will continue to review your changes in the coming months for the next patch. Happy holiday season!

**Comment by Outta-my-way-burrocrat** [comment]
While you're making those updates, could you also fix the misalignment of New Zealand's map in rivers and terrain.bmp?

**Comment by Outta-my-way-burrocrat** [comment]
Oh! I forgot to mention that Russia has its proletarian_dictatorship color again.

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 Where is the primary mod forum for this fork?

**Comment by Spartan322** [comment]
Isn't Segu.txt missing?

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 why aren't Aotearoa and Scandinavia releasable as vassals?

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 before the next release could you do a hotfix for Burundi Rwanda and Uganda? They cannot sell enough commodities to feed their people.

**Comment by Capitanloco6** [comment]
> @Capitanloco6 before the next release could you do a hotfix for Burundi Rwanda and Uganda? They cannot sell enough commodities to feed their people.

What files specifically should I look at to incorporate into the WIP build to fix this? ETA for the next patch is tomorrow so there's still time. Otherwise I can add it in the inevitable post patch hotfixes.

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 the countries mentioned have commodity RGOs like cotton and coffee, none of which sell enough to cover their farmers life needs. HPM changed the RGOs to food RGOs and added colonial decisions for the commodity RGOs.

**Comment by Outta-my-way-burrocrat** [comment]
Province RGOs in 2019 2020 2022 2034 and 2035. 
https://github.com/arkhometha/Historical-Project-Mod/blob/09afcba51fb953097dbce5b5c424f87e32ac5cc0/HPM/history/provinces/africa/2019%20-%20Entebbe.txt#L2 
https://github.com/arkhometha/Historical-Project-Mod/blob/09afcba51fb953097dbce5b5c424f87e32ac5cc0/HPM/history/provinces/africa/2020%20-%20Mbarara.txt#L2 
https://github.com/arkhometha/Historical-Project-Mod/blob/09afcba51fb953097dbce5b5c424f87e32ac5cc0/HPM/history/provinces/africa/2022%20-%20Kitgum.txt#L2 
https://github.com/arkhometha/Historical-Project-Mod/blob/09afcba51fb953097dbce5b5c424f87e32ac5cc0/HPM/history/provinces/africa/2034%20-%20Kigali.txt#L2 
https://github.com/arkhometha/Historical-Project-Mod/blob/09afcba51fb953097dbce5b5c424f87e32ac5cc0/HPM/history/provinces/africa/2035%20-%20Usumbura.txt#L2

**Comment by Outta-my-way-burrocrat** [comment]
Nevermind.

**Comment by Outta-my-way-burrocrat** [comment]
@Capitanloco6 I'm going to stop posting on the 28th, so I won't be able to maintain these PRs any longer. I give y'all permission to use any of my contributions from these PRs, just don't go out of your way to hide my work or credits.

**Pull request closed without merging**
